config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :restaurants, only: [:index, :show, :new, :create]  do
  resource :reviews, only: [:new, :create]
end
root to: 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, presence: :true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, inclusion: 0..5, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_retaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def create
    restaurant = Restaurant.new(restaurant_params)
    create_restaurant = restaurant.save
    redirect_to restaurant_path(restaurant)
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
  end

  private

  def set_retaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  private

  def review_params
  params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<div class="header text-center">
<h1>Our restaurants</h1>
<span><%= link_to "add a restaurant", new_restaurant_path %></span>
</div>

<% @restaurants.each do |restaurant| %>
  <div class="resto">
      <div class="container">
          <div class="row col-sm-10 col-sm-offset-1">
              <h2 class = "primary-attributes"><%= restaurant.name %></h2>
              <h3 class="category-list"> style:<%= restaurant.category %></h3>
              <div class="secondary-attributes">
                <p>Address: <%= restaurant.address%></p>
                <p>phone-number: <%= restaurant.phone_number%></p>
              </div>
                <%= link_to "restaurant detail", restaurant_path(restaurant.id) %>
                <%= link_to "add a review", new_restaurant_reviews_path(restaurant.id) %>
          </div>
      </div>
  </div>
  <% end %>

app/views/restaurants/new.html.erb
<h1 class="text-center">Add your restaurant</h1>
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <%= simple_form_for @restaurant do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :category %>
        <%= f.input :phone_number %>
        <%= f.submit "add a restaurant", class: "btn btn-warning" %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<h1 class= text-center><%= @restaurant.name %></h1>
<br>
<br>
<div class="resto">
  <div class="container">
      <div class="row">
       <div class="col-sm-10 col-sm-offset-1">
        <div class="primary-attributes">
          <p class="category-list"> style:<%= @restaurant.category %></p>
        </div>
        <div class="secondary-attributes">
            <p>Address: <%= @restaurant.address%></p>
            <br>
            <p>Numb: <%= @restaurant.phone_number%></p>
        </div>
       </div>
      </div>
      <% @restaurant.reviews.each do |review| %>
        <div class="row">
          <div class="col-sm-10 col-sm-offset-1">
            <div class="third-attributes">
              <p>Content:<%= review.content %></p>
              <div class="i-stars i-stars--regular-<%= review.rating %>">
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <br>
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
          <%= link_to "back", restaurants_path%>
        </div>
      </div>
  </div>

</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1 class="text-center">Add a review</h1>
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <%= simple_form_for [@restaurant, @review] do |f| %>
        <%= f.input :content %>
        <%= f.input :rating %>

        <%= f.submit "add my review", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Notification -->
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>